export const MODAL_OPEN_CREATE_TOKEN: string = "MODAL_OPEN_CREATE_TOKEN";
export const MODAL_CLOSE_CREATE_TOKEN: string = "MODAL_CLOSE_CREATE_TOKEN";

export const MODAL_OPEN_ADD_SUPPORT: string = "MODAL_OPEN_ADD_SUPPORT";
export const MODAL_CLOSE_ADD_SUPPORT: string = "MODAL_CLOSE_ADD_SUPPORT";
